import Home from "../app/page";
import useFetch from "../components/UseFetch";
import { render, screen } from "@testing-library/react";
import ApiServices from "../Services/ApiServices";
import DomainServices from "../Services/DomainServices";
import { it } from "node:test";

let plats = [
  {
    name: "bbq",
    aliments: [
      {
        ingredient: { name: "saucisses", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "chorizo à cuire BBQ", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "merguez", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0, 1],
    saison: [2],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "Cordons bleus - ptits pois carottes",
    aliments: [
      {
        ingredient: { name: "Cordon bleu", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "Petits pois-carotte", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "couscous",
    aliments: [
      {
        ingredient: { name: "merguez", typeIngredient: 0 },
        quantité: 6,
        unité: 6,
      },
      {
        ingredient: { name: "légumes à couscous surgelés", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "epices à couscous", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "semoule", typeIngredient: 2 },
        quantité: 100,
        unité: 0,
      },
      {
        ingredient: { name: "semoule epicée", typeIngredient: 2 },
        quantité: 100,
        unité: 0,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    name: "Croque monsieur béchamel",
    aliments: [
      {
        ingredient: { name: "Pain de mie", typeIngredient: 2 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 6,
        unité: 5,
      },
      {
        ingredient: { name: "Farine", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
      {
        ingredient: { name: "Gruyère rapé", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
    ],
    momentRepasPossible: [1, 0],
    saison: [3, 2, 1, 0],
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    name: "Escalopes de dinde à la crème - salsifis - pommes dauphines",
    aliments: [
      {
        ingredient: { name: "Escalope de dinde", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "salsifi", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 25,
        unité: 4,
      },
      {
        ingredient: { name: "Pommes dauphines", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 3, 2],
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    name: "jambon à griller - lentilles - salsifi",
    aliments: [
      {
        ingredient: { name: "jambon à griller", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "lentilles", typeIngredient: 2 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "salsifi", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "Omelette",
    aliments: [
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 5,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: [1, 0, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    name: "Pates carbonara",
    aliments: [
      {
        ingredient: { name: "Pates", typeIngredient: 2 },
        quantité: 400,
        unité: 0,
      },
      {
        ingredient: { name: "Lardons fumés", typeIngredient: 0 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 20,
        unité: 4,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    name: "Pates jambon",
    aliments: [
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 4,
        unité: 5,
      },
      {
        ingredient: { name: "Pates", typeIngredient: 2 },
        quantité: 400,
        unité: 0,
      },
    ],
    momentRepasPossible: [1, 0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "pizza papa chorizo",
    aliments: [
      {
        ingredient: { name: "farine pizza", typeIngredient: 1 },
        quantité: 224,
        unité: 0,
      },
      {
        ingredient: { name: "levure fraiche", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 1, unité: 0 },
      {
        ingredient: { name: "sauce pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "fromage pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "chorizo fort", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 2,
    nbrRepasPossible: 1,
  },
  {
    name: "pizza papa jambon",
    aliments: [
      {
        ingredient: { name: "farine pizza", typeIngredient: 1 },
        quantité: 224,
        unité: 0,
      },
      {
        ingredient: { name: "levure fraiche", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 1, unité: 0 },
      {
        ingredient: { name: "sauce pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "fromage pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 3,
        unité: 5,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 2,
    nbrRepasPossible: 1,
  },
  {
    name: "pizza papa jambon serrano - roquette",
    aliments: [
      {
        ingredient: { name: "farine pizza", typeIngredient: 1 },
        quantité: 224,
        unité: 0,
      },
      {
        ingredient: { name: "levure fraiche", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 5, unité: 0 },
      {
        ingredient: { name: "sauce pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "fromage pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "jambon serrano", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Roquette", typeIngredient: 2 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 2,
    nbrRepasPossible: 1,
  },
  {
    name: "pizza papa reine",
    aliments: [
      {
        ingredient: { name: "farine pizza", typeIngredient: 1 },
        quantité: 224,
        unité: 0,
      },
      {
        ingredient: { name: "levure fraiche", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 1, unité: 0 },
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 3,
        unité: 5,
      },
      {
        ingredient: { name: "sauce pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "fromage pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "champignons", typeIngredient: 3 },
        quantité: 200,
        unité: 0,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 2,
    nbrRepasPossible: 1,
  },
  {
    name: "pizza surgelée",
    aliments: [
      {
        ingredient: { name: "pizza surgelée", typeIngredient: 1 },
        quantité: 2,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "poisson - blé - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "blé", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "poisson - quinoa - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "quinoa", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "poisson - riz - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "riz", typeIngredient: 2 },
        quantité: 125,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "poisson - semoule - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "semoule", typeIngredient: 2 },
        quantité: 150,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "Purée - cordon bleus - julienne",
    aliments: [
      {
        ingredient: { name: "pommes de terre vapeur", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "Cordon bleu", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "haricots beurre", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: [2, 1, 0, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "Quiche",
    aliments: [
      {
        ingredient: { name: "pate brisée", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Lardons fumés", typeIngredient: 0 },
        quantité: 150,
        unité: 0,
      },
      {
        ingredient: { name: "Lait", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 4,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    name: "Quiche au thon",
    aliments: [
      {
        ingredient: { name: "thon", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Pate feuilletée", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Moutarde", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Tomate", typeIngredient: 3 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "Gruyère rapé", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 4,
        unité: 6,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 5, unité: 0 },
      {
        ingredient: { name: "poivre", typeIngredient: 1 },
        quantité: 5,
        unité: 0,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    name: "Quiche sans pate",
    aliments: [
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 3,
        unité: 6,
      },
      {
        ingredient: { name: "Lait", typeIngredient: 1 },
        quantité: 250,
        unité: 3,
      },
      {
        ingredient: { name: "Farine", typeIngredient: 1 },
        quantité: 100,
        unité: 0,
      },
      {
        ingredient: { name: "Gruyère rapé", typeIngredient: 1 },
        quantité: 100,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 5, unité: 0 },
      {
        ingredient: { name: "dés de jambon", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    name: "Sandwich",
    aliments: [
      {
        ingredient: { name: "Pain de mie", typeIngredient: 2 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Gruyère rapé", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 4,
        unité: 5,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    name: "Tagliatelles de légumes",
    aliments: [
      {
        ingredient: { name: "Carotte", typeIngredient: 3 },
        quantité: 300,
        unité: 0,
      },
      {
        ingredient: { name: "courgettes", typeIngredient: 3 },
        quantité: 300,
        unité: 0,
      },
    ],
    momentRepasPossible: [1, 0],
    saison: [1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    name: "Tarte tomates Mozzarella",
    aliments: [
      {
        ingredient: { name: "Pate feuilletée", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "concentré de tomates", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Tomate", typeIngredient: 3 },
        quantité: 4,
        unité: 6,
      },
      {
        ingredient: { name: "Mozzarella", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Basilic", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 1, unité: 0 },
      {
        ingredient: { name: "poivre", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
    ],
    momentRepasPossible: [1],
    saison: [0, 1, 2, 3],
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
];
let platsDansMenu = [
  {
    jour: 4,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2004728+01:00",
    isBlocked: false,
    name: "Croque monsieur béchamel",
    aliments: [
      {
        ingredient: { name: "Pain de mie", typeIngredient: 2 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 6,
        unité: 5,
      },
      {
        ingredient: { name: "Farine", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
      {
        ingredient: { name: "Gruyère rapé", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
    ],
    momentRepasPossible: [1, 0],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    jour: 4,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2008088+01:00",
    isBlocked: false,
    name: "pizza surgelée",
    aliments: [
      {
        ingredient: { name: "pizza surgelée", typeIngredient: 1 },
        quantité: 2,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: null,
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    jour: 5,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2008365+01:00",
    isBlocked: false,
    name: "Pates jambon",
    aliments: [
      {
        ingredient: { name: "jambon", typeIngredient: 0 },
        quantité: 4,
        unité: 5,
      },
      {
        ingredient: { name: "Pates", typeIngredient: 2 },
        quantité: 400,
        unité: 0,
      },
    ],
    momentRepasPossible: [1, 0],
    saison: null,
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    jour: 5,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 1,
    date: "2024-10-28T16:12:39.2008471+01:00",
    isBlocked: false,
    name: "Quiche",
    aliments: [
      {
        ingredient: { name: "pate brisée", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Lardons fumés", typeIngredient: 0 },
        quantité: 150,
        unité: 0,
      },
      {
        ingredient: { name: "Lait", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 4,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    jour: 6,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2008571+01:00",
    isBlocked: false,
    name: "poisson - quinoa - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "quinoa", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: null,
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    jour: 6,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2008675+01:00",
    isBlocked: false,
    name: "Tagliatelles de légumes",
    aliments: [
      {
        ingredient: { name: "Carotte", typeIngredient: 3 },
        quantité: 300,
        unité: 0,
      },
      {
        ingredient: { name: "courgettes", typeIngredient: 3 },
        quantité: 300,
        unité: 0,
      },
    ],
    momentRepasPossible: [1, 0],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    jour: 0,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2008919+01:00",
    isBlocked: false,
    name: "poisson - riz - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "riz", typeIngredient: 2 },
        quantité: 125,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: null,
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    jour: 0,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 2,
    date: "2024-10-28T16:12:39.2009017+01:00",
    isBlocked: false,
    name: "Quiche",
    aliments: [
      {
        ingredient: { name: "pate brisée", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Lardons fumés", typeIngredient: 0 },
        quantité: 150,
        unité: 0,
      },
      {
        ingredient: { name: "Lait", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 4,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    jour: 1,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2009114+01:00",
    isBlocked: false,
    name: "poisson - blé - ratatouille",
    aliments: [
      {
        ingredient: { name: "poisson", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "blé", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "ratatouille", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [0],
    saison: null,
    tempsPréparation: 0,
    nbrRepasPossible: 1,
  },
  {
    jour: 1,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2009212+01:00",
    isBlocked: false,
    name: "pizza papa chorizo",
    aliments: [
      {
        ingredient: { name: "farine pizza", typeIngredient: 1 },
        quantité: 224,
        unité: 0,
      },
      {
        ingredient: { name: "levure fraiche", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 1, unité: 0 },
      {
        ingredient: { name: "sauce pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "fromage pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "chorizo fort", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: null,
    tempsPréparation: 2,
    nbrRepasPossible: 1,
  },
  {
    jour: 2,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2009344+01:00",
    isBlocked: false,
    name: "Escalopes de dinde à la crème - salsifis - pommes dauphines",
    aliments: [
      {
        ingredient: { name: "Escalope de dinde", typeIngredient: 0 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "salsifi", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 25,
        unité: 4,
      },
      {
        ingredient: { name: "Pommes dauphines", typeIngredient: 2 },
        quantité: 200,
        unité: 0,
      },
    ],
    momentRepasPossible: [0],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 1,
  },
  {
    jour: 2,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2009465+01:00",
    isBlocked: false,
    name: "pizza papa jambon serrano - roquette",
    aliments: [
      {
        ingredient: { name: "farine pizza", typeIngredient: 1 },
        quantité: 224,
        unité: 0,
      },
      {
        ingredient: { name: "levure fraiche", typeIngredient: 1 },
        quantité: 1,
        unité: 0,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 5, unité: 0 },
      {
        ingredient: { name: "sauce pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      {
        ingredient: { name: "fromage pizza", typeIngredient: 1 },
        quantité: 200,
        unité: 0,
      },
      {
        ingredient: { name: "jambon serrano", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Roquette", typeIngredient: 2 },
        quantité: 1,
        unité: 6,
      },
    ],
    momentRepasPossible: [1],
    saison: null,
    tempsPréparation: 2,
    nbrRepasPossible: 1,
  },
  {
    jour: 3,
    momentRepasRetenu: 0,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2009553+01:00",
    isBlocked: false,
    name: "couscous",
    aliments: [
      {
        ingredient: { name: "merguez", typeIngredient: 0 },
        quantité: 6,
        unité: 6,
      },
      {
        ingredient: { name: "légumes à couscous surgelés", typeIngredient: 3 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "epices à couscous", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "semoule", typeIngredient: 2 },
        quantité: 100,
        unité: 0,
      },
      {
        ingredient: { name: "semoule epicée", typeIngredient: 2 },
        quantité: 100,
        unité: 0,
      },
    ],
    momentRepasPossible: [0],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
  {
    jour: 3,
    momentRepasRetenu: 1,
    nbrItérationDuPlatDansMenu: 0,
    date: "2024-10-28T16:12:39.2009655+01:00",
    isBlocked: false,
    name: "Quiche au thon",
    aliments: [
      {
        ingredient: { name: "thon", typeIngredient: 0 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Pate feuilletée", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Moutarde", typeIngredient: 1 },
        quantité: 1,
        unité: 6,
      },
      {
        ingredient: { name: "Tomate", typeIngredient: 3 },
        quantité: 2,
        unité: 6,
      },
      {
        ingredient: { name: "Gruyère rapé", typeIngredient: 1 },
        quantité: 50,
        unité: 0,
      },
      {
        ingredient: { name: "Oeufs", typeIngredient: 1 },
        quantité: 4,
        unité: 6,
      },
      {
        ingredient: { name: "Crème fraiche", typeIngredient: 1 },
        quantité: 200,
        unité: 3,
      },
      { ingredient: { name: "sel", typeIngredient: 1 }, quantité: 5, unité: 0 },
      {
        ingredient: { name: "poivre", typeIngredient: 1 },
        quantité: 5,
        unité: 0,
      },
    ],
    momentRepasPossible: [1],
    saison: null,
    tempsPréparation: 1,
    nbrRepasPossible: 2,
  },
];
let allIngredients = [
  { name: "Actimel", typeIngredient: 4 },
  { name: "Ail", typeIngredient: 1 },
  { name: "andouillettes", typeIngredient: 0 },
  { name: "Basilic", typeIngredient: 1 },
  { name: "beurre", typeIngredient: 4 },
  { name: "beurre tendre", typeIngredient: 4 },
  { name: "biscottes froment", typeIngredient: 4 },
  { name: "biscottes multicéréales", typeIngredient: 4 },
  { name: "blé", typeIngredient: 2 },
  { name: "BoeufHaché", typeIngredient: 0 },
  { name: "boulettes viande", typeIngredient: 0 },
  { name: "boulghour", typeIngredient: 2 },
  { name: "Brocoli", typeIngredient: 3 },
  { name: "café", typeIngredient: 4 },
  { name: "cannelonni", typeIngredient: 1 },
  { name: "Carotte", typeIngredient: 3 },
  { name: "Céréales", typeIngredient: 4 },
  { name: "champignons", typeIngredient: 3 },
  { name: "chorizo à cuire BBQ", typeIngredient: 0 },
  { name: "chorizo fort", typeIngredient: 0 },
  { name: "concentré de tomates", typeIngredient: 1 },
  { name: "confiture", typeIngredient: 4 },
  { name: "Cordon bleu", typeIngredient: 0 },
  { name: "Cote de porc", typeIngredient: 0 },
  { name: "courgettes", typeIngredient: 3 },
  { name: "creme enfants", typeIngredient: 4 },
  { name: "Crème fraiche", typeIngredient: 1 },
  { name: "dés de jambon", typeIngredient: 0 },
  { name: "epices à couscous", typeIngredient: 1 },
  { name: "Escalope de dinde", typeIngredient: 0 },
  { name: "Farine", typeIngredient: 1 },
  { name: "farine pizza", typeIngredient: 1 },
  { name: "Filet mignon", typeIngredient: 0 },
  { name: "Frites", typeIngredient: 2 },
  { name: "fromage à burger", typeIngredient: 1 },
  { name: "fromage chèvre", typeIngredient: 1 },
  { name: "Fromage croque Mr", typeIngredient: 2 },
  { name: "fromage pizza", typeIngredient: 1 },
  { name: "Fruits - bananes", typeIngredient: 4 },
  { name: "Fruits - clémentines", typeIngredient: 4 },
  { name: "Fruits - divers", typeIngredient: 4 },
  { name: "Fruits - kiwi", typeIngredient: 4 },
  { name: "Fruits - poires", typeIngredient: 4 },
  { name: "Fruits -pommes jaunes", typeIngredient: 4 },
  { name: "Fruits -pommes rouges", typeIngredient: 4 },
  { name: "galettes de riz", typeIngredient: 4 },
  { name: "gateaux 4h", typeIngredient: 4 },
  { name: "gateaux apéritifs", typeIngredient: 4 },
  { name: "gnocchi", typeIngredient: 2 },
  { name: "Gruyère rapé", typeIngredient: 1 },
  { name: "haricots beurre", typeIngredient: 3 },
  { name: "Haricots rouge", typeIngredient: 2 },
  { name: "Haricots verts", typeIngredient: 3 },
  { name: "Hauts de cuisse", typeIngredient: 0 },
  { name: "huile olive", typeIngredient: 1 },
  { name: "jambon", typeIngredient: 0 },
  { name: "jambon à griller", typeIngredient: 0 },
  { name: "jambon serrano", typeIngredient: 0 },
  { name: "Jus d'orange", typeIngredient: 4 },
  { name: "Jus de pomme", typeIngredient: 4 },
  { name: "knaki", typeIngredient: 0 },
  { name: "Lait", typeIngredient: 1 },
  { name: "Lardons fumés", typeIngredient: 0 },
  { name: "légumes à couscous surgelés", typeIngredient: 3 },
  { name: "légumes pour soupe", typeIngredient: 3 },
  { name: "lentilles", typeIngredient: 2 },
  { name: "levure fraiche", typeIngredient: 1 },
  { name: "merguez", typeIngredient: 0 },
  { name: "miel", typeIngredient: 1 },
  { name: "morceaux de poulet grillé", typeIngredient: 0 },
  { name: "Moutarde", typeIngredient: 1 },
  { name: "Mozzarella", typeIngredient: 1 },
  { name: "Oeufs", typeIngredient: 1 },
  { name: "oignon", typeIngredient: 1 },
  { name: "pack de Lait", typeIngredient: 4 },
  { name: "pain", typeIngredient: 4 },
  { name: "pain à hotdog", typeIngredient: 1 },
  { name: "pain burger", typeIngredient: 1 },
  { name: "Pain de mie", typeIngredient: 2 },
  { name: "parmesan", typeIngredient: 1 },
  { name: "pate brisée", typeIngredient: 1 },
  { name: "Pate feuilletée", typeIngredient: 1 },
  { name: "Pates", typeIngredient: 2 },
  { name: "Petits pois", typeIngredient: 3 },
  { name: "Petits pois-carotte", typeIngredient: 3 },
  { name: "Pilon de poulet", typeIngredient: 0 },
  { name: "pizza surgelée", typeIngredient: 1 },
  { name: "poisson", typeIngredient: 0 },
  { name: "poivre", typeIngredient: 1 },
  { name: "Pommes dauphines", typeIngredient: 2 },
  { name: "pommes de terre vapeur", typeIngredient: 2 },
  { name: "Poulet", typeIngredient: 0 },
  { name: "quinoa", typeIngredient: 2 },
  { name: "ratatouille", typeIngredient: 3 },
  { name: "ravioli", typeIngredient: 1 },
  { name: "Reblochon", typeIngredient: 1 },
  { name: "riz", typeIngredient: 2 },
  { name: "Roquette", typeIngredient: 2 },
  { name: "Salade - Sucrines", typeIngredient: 4 },
  { name: "salsifi", typeIngredient: 3 },
  { name: "sauce pizza", typeIngredient: 1 },
  { name: "Sauces - condiments", typeIngredient: 4 },
  { name: "saucisses", typeIngredient: 0 },
  { name: "sel", typeIngredient: 1 },
  { name: "semoule", typeIngredient: 2 },
  { name: "semoule epicée", typeIngredient: 2 },
  { name: "Steak", typeIngredient: 0 },
  { name: "Steak haché", typeIngredient: 0 },
  { name: "tartines multicéréales", typeIngredient: 4 },
  { name: "thon", typeIngredient: 0 },
  { name: "Tomate", typeIngredient: 3 },
  { name: "yaourt maman", typeIngredient: 4 },
  { name: "yaourt papa", typeIngredient: 4 },
];

describe("DashboardPage", () => {
  // beforeEach(() => {
  //   global.fetch = jest.fn();
  // });
  // test("Page",async () => {
  //   render(<Home />);
  //   expect(screen.getByText("Plats du Jour 0")).toBeDefined();
  // });
  test("Page2", () => {
    expect(2 + 2).toBe(4);
  });

  test("Page3", () => {
    let result = DomainServices.getPlatCompatible(2, platsDansMenu);
    expect(result.length != 25).toBeTruthy();
  });
  test("Page4", () => {
    let result = DomainServices.getPlatCompatible(2, platsDansMenu);
    expect(result.length != 25).toBeTruthy();
  });


});
